os:
  - osx
env:
  matrix:
  - INSTALL_TYPE='macpython' VERSION=2.7.10 CC=clang CXX=clang++
  - INSTALL_TYPE='macpython' VERSION=3.4.3 CC=clang CXX=clang++
  - INSTALL_TYPE='macpython' VERSION=3.5.0 CC=clang CXX=clang++
install:
- source terryfy/travis_tools.sh
- get_python_environment $INSTALL_TYPE $VERSION venv
- pip install --upgrade wheel
- pip install cython
script:
- pip wheel -v -w dist .
before_deploy:
- export DIST=$(ls ./dist)
deploy:
  provider: releases
  api_key:
    secure: c7dxz1JFSkQIOCMafs8XfPutQazgsk3H9HZBy0vqEsO0rckwVaE2cwRtdp29WzlxugT3nFtTbeZshhFIz0+6LBvEwj6zQnx41ditWKtKQSBtli1dRs9c+uNTTa4MdMffNPNq9qZCXjkfr/i+0m0Dm79XZ5gaZv6ytRB7GVUemnnYjSOLSqqIim5ozDvHx0NV/PkDt03oDkmiVR/RiRNqb20ww6B1ww0QxzaRaIMbyfnAmtnkR8SvOLpuvTw7f5WUWktxIbzPhJfE8H78EcP79LOO8Bs+rwDBqEeg5v8X6PFXsYhLSYfEkrttFq2wzA5c+e9zTrNpxDtHw0ZCFyF1HPc+E8CtE8oick24A95BQQAJr16ih6nQvnInCXJB7qTXSkF0gkM6v/y/bdhyJMyCQ6xyEE7h5K9ztqgnAnjKrrQmGLD8tOJQVr8wEdwpM5HS4wfaKHswyBta3JQtMz7LsL8VaEk5p/zjE/cLadZRyXzZKowd5naALT7vaOzdIDLxOafebBZgGe0sPqzQX9JGNowjMPDai2Z9NK+cogpbnW3OLPsY3sEd3arV3W2srlyyRwwJOr0972XPcg6ef6zuf0TrcYThEZfpz8qyVms8nPQaZPqQWoocWrWqoa8pPNKAoRcnEmakCddZvrqS00tG0RwYZQa4ELwsdtVc+S+f/9U=
  file:
    - "${DIST}"
  skip_cleanup: true
  on:
    repo: anthrotype/booleanOperations
    tags: true
